### PR TITLE
q.all | version updates | formatting | home link bug fix

### PR DESCRIPTION
**Pull request by dallincrane**
* use $q.all rather than chained promises for getAllData
* version updates for angular and angular-route
* fixed 'home' link bug -- href needs to ="/#/"
* styling/formatting all around

### CODE REVIEW

**Comment by tylermcginnis** [comment]
$q.all is great, if you know what $q is doing. It's terrible for beginners who are still trying to wrap their heads around $q, which is why it was initially left out and chained instead.

**Comment by dallincrane** [comment]
Included in the PR for two reasons:
  - saw that there was a good example of chaining promises already in the teamCtrl
  - this comment line was right above the previously chained getTeamData method in the homeService:  
    `//look into $q.all for a cleaner way to resolve multiple promises in a row.`  
    read that line like it was a note-to-self or for other curriculum developers, rather than to students.

More than happy to revert it back. Possibly leave the the $q.all solution commented out at the bottom of the file?

I guess there is a larger question to this. Are solution/test branches meant to be there for the students or the mentors who are reviewing the project the next day and further development/updates of the project? Got the impression from my cohort that they were there for the latter.

**Comment by jacob-israel-turner** [comment]
I think it needs to be noted that there is no promise chaining going anywhere in this project, or any project.  There are only nested callbacks.

I think we should discuss and consider teaching promise chaining and possibly `q.all()` in future cohorts.

**Comment by jacob-israel-turner** [comment]
As for the solution branch right now, I think it would be wise to have the nested callbacks as the default solution, then use `q.all()` or promise chaining as  second/third solution commented out at the bottom.

**Pull request merged**
